app:
  name: test_app
  mode: dev

server:
  port: 8081
  prefix: /api
  cores:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["*"]
    expose_headers: ["*"]

log:
  level: warn
  path: /web_app/logs
  filename: web_app.log
  max_size: 20
  max_age: 30
  max_backups: 5

database:
  type: mysql
  host: localhost
  port: 3306
  name: test_db
  user: root
  password: 123456

redis:
  host: localhost
  port: 6379
  db: 0

email:
  host: smtp.qq.com
  port: 465
  user: