app:
  name: test_app
  mode: dev

server:
  port: 8081
  prefix: /local

log:
  level: debug
  path: /web_app/logs
  filename: web_app.log
  max_backups: 5

database:
  type: mysql
  host: localhost
  port: 3306
  name: test_db
  user: root
  password: rr987654321

redis:
  host: localhost
  port: 6379
  password: rr987654321
  db: 0
